import "@/styles/globals.css";

import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={" w-full scroll-mt-12"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
